- hosts: localhost
  gather_facts: false
  tasks:
    - name: test nodeping
      nodeping-check-http:
        label: ya.ru
        url: http://ya.ru
        interval: 30
        token: "{{ lookup('env','NODEPING_TOKEN') }}"
        notifications:
          - name: myslack
            delay: 0
            shedule: Days
          - name: general
            delay: 0
            shedule: All
            type: group
        state: present
